Step5のご確認を宜しくお願い致します。
m-ohno30/manyo_kadai pull request #5
Opened 2020-10-10 08:59 UTC by m-ohno30

Step５を実装致しました。
Step５をherokuにデプロイ済みです。
ご確認を宜しくお願い致します。

2020-10-10 09:58 UTC, yuji91 requested changes
こちらコーディングレベルでの指摘を行いました。

2020-10-10 09:58 UTC, yuji91 commented on app/controllers/labels_controller.rb
> +  end
```suggestion
  def edit; end
```

2020-10-10 09:58 UTC, yuji91 commented on app/controllers/labels_controller.rb
> +  end
respond_toを記載する必要が無いように思われます。gem jbuilderを有効化していると、rails g コマンド実行時に生成されると思うので、不要であればgem自体をコメントアウトか削除して良いと思います。
```suggestion
  def create
    @label = Label.new(label_params)
    if @label.save
      redirect_to @label, notice: 'Label was successfully created.'
    else
      render :new
    end
  end
```

2020-10-10 09:58 UTC, yuji91 commented on app/controllers/tasks_controller.rb
> +    #binding.pry
不要なコメントは削除をお願いします。

2020-10-10 09:58 UTC, yuji91 commented on app/controllers/tasks_controller.rb
> +    end
こちら1行で実行しても良いかと思います。
```suggestion
    @task.tasklabels.delete_all unless params[:task][:label_ids]
```

2020-10-10 09:58 UTC, yuji91 commented on app/views/admin/users/show.html.erb
> +
不要な改行かと思われます。

2020-10-10 09:58 UTC, yuji91 commented on app/views/tasks/_form.html.erb
> +    <% Label.all.each do |label| %>
Viewファイルから直接Modelを使ってDBにアクセスするのは良くないですね。

余力があればControllerからインスタンス変数を使って参照するようにしてください。

2020-10-10 09:58 UTC, yuji91 commented on db/migrate/20201004072216_create_labels.rb
> +      t.string :name
こちらnull制約はなくても大丈夫でしょうか。

2020-10-10 09:58 UTC, yuji91 commented on db/seeds.rb
> +  Tasklabel.create!(task_id: rand(1..20), label_id: rand(1..10))
Tasklabelのtask_idとlabel_idが同じ組み合わせのデータが複数回作成されてしまう可能性がある気がしますが、いかがでしょうか？

2020-10-10 09:58 UTC, yuji91 commented on spec/system/label.spec.rb
> +      #save_and_open_page
こちら不要なコメントかと思われます。

2020-10-10 09:58 UTC, yuji91 commented on spec/system/label.spec.rb
> +    FactoryBot.create(:tasklabel, task:@second_task, label:@third_label)
FactoryBotという記載は設定ファイルに追記することで省略できますね。

2020-10-11 01:35 UTC, yuji91 commented
指摘事項については、内容ごとにコミットの単位を分けた方が良いですね。そうでないと、どの指摘が修正されて、何が修正されていないのかが分かりづらいです。

また、コミットメッセージについても「指摘を修正したこと」ではなく「どのような意図でどんな修正を行ったか」を記載するべきです。
`Fix:`のようなプレフィックスをつけることで可読性も上がります。
https://www.tam-tam.co.jp/tipsnote/program/post16686.html

a67b585 とコミットIDを半角スペース区切りで記載するとリンクになるので、指摘事項のコメントに対応するコミットIDを返信するのが望ましいです。

2020-10-11 09:20 UTC, m-ohno30 commented
伊藤さん
ご指摘ありがとうございます。
課題クリアすることを優先して、雑な対応となってしまいました。
コミットする際のコメントは、詳しく書くことを常に意識するように心掛けます！

今回は、時間がなかった為、ラベル作成機能を後回しにしております。
課題クリア後にご指摘頂いた箇所を再度確認して、追加要件と共に実装したいと考えております。

2020-10-11 14:30 UTC, merged